import testImg0 from "@/assets/images/program/img_program_thumbnail.png";
import testImg1 from "@/assets/images/program/img_program_ex1.png";
import testImg2 from "@/assets/images/program/img_program_ex2.png";
import testImg3 from "@/assets/images/program/img_program_ex3.png";
import testImg4 from "@/assets/images/program/img_program_ex4.png";
import testImg5 from "@/assets/images/program/img_program_ex5.png";
import testImg6 from "@/assets/images/program/img_program_ex6.png";
import testImg7 from "@/assets/images/program/img_program_ex7.png";
import testImg8 from "@/assets/images/program/img_program_ex8.png";
import testImg9 from "@/assets/images/program/img_program_ex9.png";
import testImg10 from "@/assets/images/program/img_program_ex10.png";

const _programList = [
  {
    비교과_키: "0",
    모집_구분: "ing",
    eliTitle: "글로벌 시대. 외국어만 잘해서는 안된다.",
    cdNm: "글로컬리더십",
    cdNm_키: "A001001",
    모집_시작_기간: new Date(),
    모집_종료_기간: new Date(),
    운영_시작_기간: new Date(),
    운영_종료_기간: new Date(),
    비교과_대상: "재학생|졸업생",
    총_찜_수: 1020,
    내_찜_여부: "N",
    비교과_마일리지: 1000,
    신청자_수: 19,
    모집자_수: 20,
    대기신청_수: 0,
    대기모집_수: 20,
    썸네일_경로: testImg1,
    팀_여부: "N",
  },
  {
    비교과_키: "1",
    모집_구분: "plan",
    eliTitle: "힙하게 살아보자! YOLO 라이프, 주의해야 할 점은?",
    cdNm: "감성역량",
    cdNm_키: "A001001",
    모집_시작_기간: new Date(),
    모집_종료_기간: new Date(),
    운영_시작_기간: new Date(),
    운영_종료_기간: new Date(),
    비교과_대상: "재학생",
    총_찜_수: 100,
    내_찜_여부: "N",
    비교과_마일리지: 1000,
    신청자_수: 0,
    모집자_수: 100,
    대기신청_수: 0,
    대기모집_수: 20,
    썸네일_경로: testImg2,
    팀_여부: "Y",
  },
  {
    비교과_키: "2",
    모집_구분: "plan",
    eliTitle: "범죄자의 심리에서 알아보는 집단에 관한 고찰",
    cdNm: "문해력",
    cdNm_키: "A001001",
    모집_시작_기간: new Date(),
    모집_종료_기간: new Date(),
    운영_시작_기간: new Date(),
    운영_종료_기간: new Date(),
    비교과_대상: "휴학생",
    총_찜_수: 100,
    내_찜_여부: "N",
    비교과_마일리지: 1000,
    신청자_수: 0,
    모집자_수: 20,
    대기신청_수: 0,
    대기모집_수: 20,
    썸네일_경로: testImg3,
    팀_여부: "Y",
  },
  {
    비교과_키: "3",
    모집_구분: "plan",
    eliTitle: "챗 GPT와 함께하는 AI 채팅",
    cdNm: "지식이해역량",
    cdNm_키: "A001001",
    모집_시작_기간: new Date(),
    모집_종료_기간: new Date(),
    운영_시작_기간: new Date(),
    운영_종료_기간: new Date(),
    비교과_대상: "재학생",
    총_찜_수: 100,
    내_찜_여부: "Y",
    비교과_마일리지: 0,
    신청자_수: 0,
    모집자_수: 20,
    대기신청_수: 0,
    대기모집_수: 20,
    썸네일_경로: testImg4,
    팀_여부: "Y",
  },
  {
    비교과_키: "4",
    모집_구분: "ing",
    eliTitle: "나를 찾는 여행, 어디서부터 시작해야할까?",
    cdNm: "정보활용역량",
    cdNm_키: "A001001",
    모집_시작_기간: new Date(),
    모집_종료_기간: new Date(),
    운영_시작_기간: new Date(),
    운영_종료_기간: new Date(),
    비교과_대상: "휴학생|졸업생",
    총_찜_수: 100,
    내_찜_여부: "Y",
    비교과_마일리지: 1000,
    신청자_수: 19,
    모집자_수: 20,
    대기신청_수: 0,
    대기모집_수: 20,
    썸네일_경로: testImg5,
    팀_여부: "Y",
  },
  {
    비교과_키: "5",
    모집_구분: "plan",
    eliTitle: "프레젠테이션으로 관중의 마음을 잡아보자",
    cdNm: "융합역량",
    cdNm_키: "A001001",
    모집_시작_기간: new Date(),
    모집_종료_기간: new Date(),
    운영_시작_기간: new Date(),
    운영_종료_기간: new Date(),
    비교과_대상: "졸업생",
    총_찜_수: 100,
    내_찜_여부: "N",
    비교과_마일리지: 1000,
    신청자_수: 0,
    모집자_수: 20,
    대기신청_수: 0,
    대기모집_수: 20,
    썸네일_경로: testImg6,
    팀_여부: "N",
  },
  {
    비교과_키: "6",
    모집_구분: "ing",
    eliTitle: "창의적으로 생각하기 (졸업생 강연)",
    cdNm: "창의역량",
    cdNm_키: "A001001",
    모집_시작_기간: new Date(),
    모집_종료_기간: new Date(),
    운영_시작_기간: new Date(),
    운영_종료_기간: new Date(),
    비교과_대상: "졸업생",
    총_찜_수: 100,
    내_찜_여부: "Y",
    비교과_마일리지: 1000,
    신청자_수: 19,
    모집자_수: 20,
    대기신청_수: 0,
    대기모집_수: 20,
    썸네일_경로: testImg7,
    팀_여부: "N",
  },
  {
    비교과_키: "7",
    모집_구분: "ing",
    eliTitle: "우리가 몰랐던 7가지 뇌과학",
    cdNm: "융합역량",
    cdNm_키: "A001001",
    모집_시작_기간: new Date(),
    모집_종료_기간: new Date(),
    운영_시작_기간: new Date(),
    운영_종료_기간: new Date(),
    비교과_대상: "휴학생",
    총_찜_수: 100,
    내_찜_여부: "Y",
    비교과_마일리지: 1000,
    신청자_수: 19,
    모집자_수: 20,
    대기신청_수: 0,
    대기모집_수: 20,
    썸네일_경로: testImg8,
    팀_여부: "N",
  },
  {
    비교과_키: "8",
    모집_구분: "ing",
    eliTitle: "미래 우주산업의 전망과 물류시장의 연관성",
    cdNm: "지식이해역량",
    cdNm_키: "A001001",
    모집_시작_기간: new Date(),
    모집_종료_기간: new Date(),
    운영_시작_기간: new Date(),
    운영_종료_기간: new Date(),
    비교과_대상: "재학생",
    총_찜_수: 100,
    내_찜_여부: "Y",
    비교과_마일리지: 1000,
    신청자_수: 19,
    모집자_수: 20,
    대기신청_수: 0,
    대기모집_수: 20,
    썸네일_경로: testImg9,
    팀_여부: "N",
  },
  {
    비교과_키: "9",
    모집_구분: "ing",
    eliTitle: "리더의 동기부여 대화법을 알아보자",
    cdNm: "대인관계",
    cdNm_키: "A001001",
    모집_시작_기간: new Date(),
    모집_종료_기간: new Date(),
    운영_시작_기간: new Date(),
    운영_종료_기간: new Date(),
    비교과_대상: "재학생",
    총_찜_수: 100,
    내_찜_여부: "Y",
    비교과_마일리지: 1000,
    신청자_수: 19,
    모집자_수: 20,
    대기신청_수: 0,
    대기모집_수: 20,
    썸네일_경로: testImg10,
    팀_여부: "Y",
  },
];

export default _programList;
