import LctrList from "./LctrList.vue";
import ExamList from "./ExamList.vue";
import ReportList from "./ReportList.vue";
import ReferList from "./ReferList.vue";
import QnaList from "./QnaList.vue";
import NoticeList from "./NoticeList.vue";
import ClassMng from "./ClassMng.vue";
import ClassSetup from "./ClassSetup.vue";
import EcpAplcn from "./EcpAplcn.vue";
//import AttendScore from "./AttendScore.vue";
export { LctrList, ExamList, ReportList, ReferList, QnaList, NoticeList, ClassMng, ClassSetup, EcpAplcn };
